### ISSUE TITLE
Could not open remote tab. Error: Path argument must be a string

### ISSUE THREAD

**Issue by pochubayk** [eablokker/nova-tabs-sidebar#1]
Not able to have sidebar open or sort remote files. 

NOVA 9.5 Build 437303

**Comment by eablokker** [comment]
I've just released a new version rewritten with Typescript. It may have resolved some issues. Could you please try it?

There is currently a limitation if you have a local tab and a remote tab with the same filename it will get the two tabs confused.

Not sure what could be causing your issue.

Do you have your system set to another language other than English? That could potentially cause an issue. Or maybe if your project name or project folder name have special characters.

Any other details on how to recreate the error?

In future updates I could add more detailed error messages to help track down where exactly the error is happening.

**Comment by eablokker** [comment]
@pochubayk I think you must have had a workspace open that was not bound to a folder or project. I found a number of issues with this kind of workspace, and issues when file browser & terminal tabs are active. I fixed these issues in 1.4.1 just released. Let me know if that solves your issue.

**Comment by eablokker** [comment]
Closing as I believe I have fixed the issue.

**Comment by FishnetNewMedia** [comment]
Looking to reopen this issue. I am working on a remote project and like the origin poster I cannot open a file by clicking the file name nor can it be opened a file by right-clicking the file name and selecting "Open". Many of the other options listed when right-clicking a file are disabled or don't work.

**Comment by eablokker** [comment]
@FishnetNewMedia 

Can you provide any more details?

- Latest version of Nova?
- Is it a particular remote file that won't open or all of them?
- Have you given Nova accessibility permissions in System Preferences?
- Are you using Nova in another language?
- Are there any special characters in your file name or path on the remote server?

There is a current limitation where if you have a local file and a remote file open, both with the same file name, it may open the local file instead when you click on the remote file.

I have disabled certain right-click options like "show in finder" and "copy relative path" because they don't make sense for remote files, so that is to be expected.

**Comment by FishnetNewMedia** [comment]
Thank you Austen.

Yes, latest version of Nova (version 10, released 10/26/22).

All remote files won't open (and close via the menu).

I don't see any accessibility permissions granted for Nova (System Preferences > Accessibility), nor do I see any special configurations for System Preferences > Security & Privacy >  Accessibility.

I'm using Nova in English only.

There are no special characters in the file name or path to the remote server, just alpha characters and underscores for folders, and alpha characters, underscores, and periods for files.

I've tested this with a project on my local system and the files open as expected.

Please let me know if there's anything else I can do to help.

**Comment by eablokker** [comment]
Looks like the accessibility permissions is the issue. The extension needs to invoke Applescript in order to perform certain commands like opening remote tabs, and that requires that Nova has accessibility permissions. It should have prompted you to enable permissions when you tried to perform those actions.

Look under System Preferences > Security & Privacy > Privacy > Accessibility, and if Nova is not in the list, try adding it manually using the + button.

Let me know if that works.

**Comment by FishnetNewMedia** [comment]
I've added Nova to System Preferences > Security & Privacy > Privacy > Accessibility but it still can't open the tabs despite rebooting Nova and my system. Full disclosure, I was prompted by Nova for granting permission to make changes to my computer yesterday and I declined not realizing it was related to this extension.

**Comment by eablokker** [comment]
I see. I'm actually not sure how to add back the permissions once you have denied them. That should have done it.

Try also looking in System Preferences > Security & Privacy > Privacy > Automation, and see if you can find Nova in that list and check on "System Events" under Nova.

**Comment by FishnetNewMedia** [comment]
Adjusting the System Preferences > Security & Privacy > Privacy > Automation preference did the trick. Under the Nova.app there was a "System Events.app" option that was currently unchecked. Checking this option as well as adding Nova to the System Preferences > Security & Privacy > Privacy > Accessibility list enabled the ability to open and close tabs. Thank you Austen!
