### ISSUE TITLE
"Clean Up By Tab Bar Order" doesn't do anything

### ISSUE THREAD

**Issue by ryndshn** [eablokker/nova-tabs-sidebar#9]
Title! Cleaning up by alpha and kind does work, but cleaning up by tab bar order doesn't do anything (just stays the same as whatever the previous order was).

Let me know if it's possible to add any context to this! Thank you

**Comment by eablokker** [comment]
Hi @ryndshn.

Make sure you have given Nova accessibility privileges in System Preferences/Settings -> Security and Privacy -> Privacy.

Also make sure you give Nova permission for System Events, under Automation in that same settings pane.

The extension uses AppleScript in the background to look inside the Window dropdown menu to get the list of open tabs in your project. That's why those permissions are needed.

If your Nova workspace doesn't have a project associated with it, or your project name or any tab names have any weird characters in them, that could potentially cause a problem. Is any of that true for you?
